# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C06
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe

Microsoft:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	FunctionObjects.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe

g++:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	FunctionObjects.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe

edg:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	FunctionObjects.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


CopyInts.exe: CopyInts.cpp

CopyStrings.exe: CopyStrings.cpp

CopyVector.exe: CopyVector.cpp

InsertVector.exe: InsertVector.cpp

CopyInts2.exe: CopyInts2.cpp

CopyStrings2.exe: CopyStrings2.cpp

ReplaceStrings.exe: ReplaceStrings.cpp

CopyInts3.exe: CopyInts3.cpp

CopyIntsToFile.exe: CopyIntsToFile.cpp

CopyIntsFromFile.exe: CopyIntsFromFile.cpp

GreaterThanN.exe: GreaterThanN.cpp

CopyInts4.exe: CopyInts4.cpp

CountNotEqual.exe: CountNotEqual.cpp

FunctionObjects.exe: FunctionObjects.cpp

FBinder.exe: FBinder.cpp

BinderValue.exe: BinderValue.cpp

PtrFun1.exe: PtrFun1.cpp

PtrFun2.exe: PtrFun2.cpp

MemFun1.exe: MemFun1.cpp

MemFun2.exe: MemFun2.cpp

FindBlanks.exe: FindBlanks.cpp

MemFun3.exe: MemFun3.cpp

ComposeTry.exe: ComposeTry.cpp

ComposeFinal.exe: ComposeFinal.cpp

FillGenerateTest.exe: FillGenerateTest.cpp

Counting.exe: Counting.cpp

Manipulations.exe: Manipulations.cpp

SearchReplace.exe: SearchReplace.cpp

Comparison.exe: Comparison.cpp

Removing.exe: Removing.cpp

SortedSearchTest.exe: SortedSearchTest.cpp

MergeTest.exe: MergeTest.cpp

SetOperations.exe: SetOperations.cpp

ForEach.exe: ForEach.cpp

Transform.exe: Transform.cpp

CalcInventory.exe: CalcInventory.cpp

TransformNames.exe: TransformNames.cpp

SpecialList.exe: SpecialList.cpp

NumericTest.exe: ../TestSuite/Test.$(OBJEXT) NumericTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)NumericTest.exe NumericTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	NumericTest.exe
endif

NumericTest.$(OBJEXT): NumericTest.cpp
