/*******************************************************
*     MYCPLUS Sample Code - http://www.mycplus.com     *
*                                                     *
*   This code is made available as a service to our   *
*      visitors and is provided strictly for the      *
*               purpose of illustration.              *
*                                                     *
* Please direct all inquiries to saqib at mycplus.com *
*******************************************************/



/*Muhammad Saqib,Zia Ur Rehman,Rizwan Iqbal.

Project: Make an IDE for C Language
Submitted to Mr. Danish*/
#include<process.h>
#include<string.h>
#include<stdio.h>
#include<conio.h>
#include<dos.h>
#include<iostream.h>
#include<graphics.h>

#include<msg.h>
#include"menu1.h"
#include<menu2.h>
#include<menu_sea.h>
#include<menu_run.h>
#include<menu_com.h>
#include<project1.h>
#include<graph_me.h>
void main()
{       graph();
       project1();

}













