/*
This source code is provided by Muhammad Saqib MYCPLUS Online Community WEbsite.
You are free to modify and change this code as per your requirements.

Website: http://4-tech-support.com/
Email:   msaqib@4-tech-support.com



*/


/*Muhammad Saqib,Zia Ur Rehman,Rizwan Iqbal.

Project: Make an IDE for C Language
Submitted to Mr. Danish*/
#include<process.h>
#include<string.h>
#include<stdio.h>
#include<conio.h>
#include<dos.h>
#include<iostream.h>
#include<graphics.h>

#include<msg.h>
#include"menu1.h"
#include<menu2.h>
#include<menu_sea.h>
#include<menu_run.h>
#include<menu_com.h>
#include<project1.h>
#include<graph_me.h>
void main()
{       graph();
       project1();

}













