# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C07
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	BasicSequenceOperations.exe \
	VectorCoreDump.exe \
	StringDeque.exe \
	IndexingVsAt.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	WordList.exe \
	WordList2.exe \
	TokenIteratorTest.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	VectorOfBool.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	ProgVals.$(OBJEXT) \
	ProgValTest.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Thesaurus.exe \
	Stlshape2.exe \
	Ring.exe

Microsoft:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	RawStorageIterator.exe \
	BasicSequenceOperations.exe \
	VectorOverflow.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	StringDeque.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	IndexingVsAt.exe \
	ListStability.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	Swapping.exe \
	WordList.exe \
	WordList2.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	BitSet.exe \
	VectorOfBool.exe \
	AssociativeBasics.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	ProgVals.$(OBJEXT) \
	ProgValTest.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Stlshape2.exe \
	Ring.exe \
	Valarray1.exe \
	Valarray2.exe

g++:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	RawStorageIterator.exe \
	BasicSequenceOperations.exe \
	VectorOverflow.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	StringDeque.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	IndexingVsAt.exe \
	ListStability.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	Swapping.exe \
	WordList.exe \
	WordList2.exe \
	TokenIteratorTest.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	BitSet.exe \
	VectorOfBool.exe \
	AssociativeBasics.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	ProgVals.$(OBJEXT) \
	ProgValTest.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Stlshape2.exe \
	Ring.exe \
	Valarray1.exe \
	Valarray2.exe

edg:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	RawStorageIterator.exe \
	BasicSequenceOperations.exe \
	VectorOverflow.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	StringDeque.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	IndexingVsAt.exe \
	ListStability.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	Swapping.exe \
	WordList.exe \
	WordList2.exe \
	TokenIteratorTest.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	BitSet.exe \
	VectorOfBool.exe \
	AssociativeBasics.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	ProgVals.$(OBJEXT) \
	ProgValTest.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Thesaurus.exe \
	Stlshape2.exe \
	Ring.exe \
	MapVsHashMap.exe \
	Valarray1.exe \
	Valarray2.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


Intset.exe: Intset.cpp

WordSet.exe: WordSet.cpp

Stlshape.exe: Stlshape.cpp

StringVector.exe: StringVector.cpp

FileEditor.$(OBJEXT): FileEditor.cpp

FEditTest.exe: FileEditor.$(OBJEXT) FEditTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FEditTest.exe FEditTest.$(OBJEXT) FileEditor.$(OBJEXT)

FEditTest.$(OBJEXT): FEditTest.cpp
Apply.exe: Apply.cpp

Reversible.exe: Reversible.cpp

Inserters.exe: Inserters.cpp

StreamIt.exe: StreamIt.cpp

StreambufIterator.exe: StreambufIterator.cpp

RawStorageIterator.exe: RawStorageIterator.cpp

BasicSequenceOperations.exe: BasicSequenceOperations.cpp

VectorOverflow.exe: VectorOverflow.cpp

VectorCoreDump.exe: VectorCoreDump.cpp

VectorInsertAndErase.exe: VectorInsertAndErase.cpp

StringDeque.exe: StringDeque.cpp

DequeConversion.exe: DequeConversion.cpp

DequeOverflow.exe: DequeOverflow.cpp

IndexingVsAt.exe: IndexingVsAt.cpp

ListStability.exe: ListStability.cpp

ListSpecialFunctions.exe: ListSpecialFunctions.cpp

UniqueList.exe: UniqueList.cpp

ListVsSet.exe: ListVsSet.cpp

Swapping.exe: Swapping.cpp

WordList.exe: WordList.cpp

WordList2.exe: WordList2.cpp

TokenIteratorTest.exe: TokenIteratorTest.cpp

Stack1.exe: Stack1.cpp

Stack2.exe: Stack2.cpp

Stack3.exe: Stack3.cpp

BankTeller.exe: BankTeller.cpp

PriorityQueue1.exe: PriorityQueue1.cpp

PriorityQueue2.exe: PriorityQueue2.cpp

PriorityQueue3.exe: PriorityQueue3.cpp

PriorityQueue4.exe: PriorityQueue4.cpp

PriorityQueue5.exe: PriorityQueue5.cpp

PriorityQueue6.exe: PriorityQueue6.cpp

PriorityQueue7.exe: PriorityQueue7.cpp

PriorityQueue8.exe: PriorityQueue8.cpp

BitSet.exe: BitSet.cpp

VectorOfBool.exe: VectorOfBool.cpp

AssociativeBasics.exe: AssociativeBasics.cpp

NoisyMap.exe: ../TestSuite/Test.$(OBJEXT) NoisyMap.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)NoisyMap.exe NoisyMap.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	NoisyMap.exe
endif

NoisyMap.$(OBJEXT): NoisyMap.cpp
AssocInserter.exe: AssocInserter.cpp

WordCount.exe: WordCount.cpp

ProgVals.$(OBJEXT): ProgVals.cpp

ProgValTest.exe: ProgVals.$(OBJEXT) ProgValTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ProgValTest.exe ProgValTest.$(OBJEXT) ProgVals.$(OBJEXT)

ProgValTest.$(OBJEXT): ProgValTest.cpp
WildLifeMonitor.exe: WildLifeMonitor.cpp

MultiSet1.exe: MultiSet1.cpp

MultiSetWordCount.exe: MultiSetWordCount.cpp

Thesaurus.exe: Thesaurus.cpp

Stlshape2.exe: Stlshape2.cpp

Ring.exe: Ring.cpp

MapVsHashMap.exe: MapVsHashMap.cpp

Valarray1.exe: Valarray1.cpp

Valarray2.exe: Valarray2.cpp

