# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C04
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Sbufget.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	DateIOTest.exe \
	Ostring.exe \
	HTMLStripper2.exe \
	Unitbuf.exe \
	Format.exe \
	Manips.exe \
	InputWidth.exe \
	nl.exe \
	Effector.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalogger.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe

Microsoft:  \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Sbufget.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	DateIOTest.exe \
	Ostring.exe \
	HTMLStripper2.exe \
	StringSeeking.exe \
	Unitbuf.exe \
	Format.exe \
	Manips.exe \
	InputWidth.exe \
	nl.exe \
	Effector.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalogger.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe \
	Locale.exe \
	Facets.exe

g++:  \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Sbufget.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	DateIOTest.exe \
	Ostring.exe \
	HTMLStripper2.exe \
	StringSeeking.exe \
	Unitbuf.exe \
	Format.exe \
	Manips.exe \
	InputWidth.exe \
	nl.exe \
	Effector.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalogger.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe

edg:  \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Sbufget.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	DateIOTest.exe \
	Ostring.exe \
	HTMLStripper2.exe \
	StringSeeking.exe \
	Unitbuf.exe \
	Format.exe \
	Manips.exe \
	InputWidth.exe \
	nl.exe \
	Effector.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalogger.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe \
	Facets.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


FileClass.$(OBJEXT): FileClass.cpp

FileClassTest.exe: FileClass.$(OBJEXT) FileClassTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FileClassTest.exe FileClassTest.$(OBJEXT) FileClass.$(OBJEXT)

FileClassTest.$(OBJEXT): FileClassTest.cpp
Iosexamp.exe: Iosexamp.cpp

Strfile.exe: Strfile.cpp

Stype.exe: Stype.cpp

Sbufget.exe: Sbufget.cpp

Seeking.exe: Seeking.cpp

Iofile.exe: Iofile.cpp

Istring.exe: Istring.cpp

DateIOTest.exe: ../C02/Date.$(OBJEXT) DateIOTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)DateIOTest.exe DateIOTest.$(OBJEXT) ../C02/Date.$(OBJEXT)

DateIOTest.$(OBJEXT): DateIOTest.cpp
Ostring.exe: Ostring.cpp

HTMLStripper2.exe: ../c03/replaceAll.$(OBJEXT) HTMLStripper2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)HTMLStripper2.exe HTMLStripper2.$(OBJEXT) ../c03/replaceAll.$(OBJEXT)

HTMLStripper2.$(OBJEXT): HTMLStripper2.cpp
StringSeeking.exe: StringSeeking.cpp

Unitbuf.exe: Unitbuf.cpp

Format.exe: Format.cpp

Manips.exe: Manips.cpp

InputWidth.exe: InputWidth.cpp

nl.exe: nl.cpp

Effector.exe: Effector.cpp

Cppcheck.exe: Cppcheck.cpp

Showerr.exe: Showerr.cpp

Datalogger.$(OBJEXT): Datalogger.cpp

Datagen.exe: DataLogger.$(OBJEXT) Datagen.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Datagen.exe Datagen.$(OBJEXT) DataLogger.$(OBJEXT)

Datagen.$(OBJEXT): Datagen.cpp
Datascan.exe: DataLogger.$(OBJEXT) Datascan.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Datascan.exe Datascan.$(OBJEXT) DataLogger.$(OBJEXT)

Datascan.$(OBJEXT): Datascan.cpp
Locale.exe: Locale.cpp

Facets.exe: Facets.cpp

